'use strict';

/* eslint-disable max-len */

// Code generator for register-tiled COMPLEX zgemm micro-kernels (ESM output).
//
// Emits variants/gen-{MR}x{NR}.js: an MR x NR *complex* register tile in
// dot-product form. Each C(i,j) is a complex accumulator (two doubles) held in
// registers across the whole K loop, so C is touched once and every A/B load is
// reused across the tile — the complex analogue of bench/dgemm-opt/gen-tile.js.
//
// A single general-stride code path covers all 9 transpose/conjugate mode
// combinations (op in {N,T,C} for A and B):
//   - transpose folds into effective row/col strides (like dgemm v4), and
//   - conjugation folds into a HOISTED sign multiplier on the imaginary part
//     (csa/csb = +/-1), NOT a per-element branch.
//
// Complex product uses the faithful 4-multiply / 2-add form (no Gauss/Karatsuba:
// that changes per-element rounding, off-policy). All arithmetic runs on the
// reinterpret-complex128 Float64 view; strides/offsets are doubled internally
// exactly as the reference does.
//
// Register budget note (the flagship finding): a complex accumulator is 2
// doubles, so an MRxNR tile costs 2*MR*NR accumulator doubles plus 2*MR+2*NR
// operand doubles. V8 spills past ~16 live f64. 2x2 = 8 acc doubles (fits);
// 4x2/2x4 = 16 acc doubles (marginal — swept to confirm the spill).

var fs = require( 'fs' );
var path = require( 'path' );

function gen( MR, NR ) {
	var L = [];
	var r, c;
	function w( s ) { L.push( s ); }

	w( '/* eslint-disable */' );
	w( '' );
	w( '// AUTO-GENERATED by gen-tile.js. Complex tile = ' + MR + 'x' + NR + ' (MR x NR). Do not edit by hand.' );
	w( '' );
	w( "import reinterpret from '@stdlib/strided/base/reinterpret-complex128/lib/index.js';" );
	w( "import real from '@stdlib/complex/float64/real/lib/index.js';" );
	w( "import imag from '@stdlib/complex/float64/imag/lib/index.js';" );
	w( '' );
	w( 'function zgemm( transa, transb, M, N, K, alpha, A, sa1, sa2, oa, B, sb1, sb2, ob, beta, C, sc1, sc2, oc ) {' );

	// Declare complex accumulators FIRST (V8 register allocation is sensitive to
	// declaration order; give the hot accumulators priority — see dgemm study).
	var accs = [];
	for ( c = 0; c < NR; c++ ) { for ( r = 0; r < MR; r++ ) { accs.push( 'c'+r+'_'+c+'R', 'c'+r+'_'+c+'I' ); } }
	w( '\tvar ' + accs.join( ', ' ) + ';' );
	var aops = []; for ( r = 0; r < MR; r++ ) { aops.push( 'a'+r+'R', 'a'+r+'I' ); }
	var bops = []; for ( c = 0; c < NR; c++ ) { bops.push( 'b'+c+'R', 'b'+c+'I' ); }
	w( '\tvar ' + aops.concat( bops ).join( ', ' ) + ';' );
	var pas = []; for ( r = 0; r < MR; r++ ) { pas.push( 'pa'+r ); }
	var pbs = []; for ( c = 0; c < NR; c++ ) { pbs.push( 'pb'+c ); }
	w( '\tvar ' + pas.concat( pbs ).join( ', ' ) + ';' );
	w( '\tvar alphaR, alphaI, betaR, betaI, nota, notb, csa, csb;' );
	w( '\tvar Av, Bv, Cv, ar, ak, bk, bn, sc1d, sc2d, oa2, ob2, oc2;' );
	w( '\tvar i, j, l, ii, jj, mb, nb, pak, pbk, pc, pcc, pa, pb;' );
	w( '\tvar sR, sI, aR, aI, bR, bI, cR, cI, outR, outI;' );
	w( '' );
	w( '\tif ( M === 0 || N === 0 ) { return C; }' );
	w( '\talphaR = real( alpha ); alphaI = imag( alpha );' );
	w( '\tbetaR = real( beta ); betaI = imag( beta );' );
	w( '\tif ( alphaR === 0.0 && alphaI === 0.0 && betaR === 1.0 && betaI === 0.0 ) { return C; }' );
	w( '\tnota = ( transa === \'no-transpose\' ); notb = ( transb === \'no-transpose\' );' );
	w( '\tcsa = ( transa === \'conjugate-transpose\' ) ? -1.0 : 1.0;' );
	w( '\tcsb = ( transb === \'conjugate-transpose\' ) ? -1.0 : 1.0;' );
	w( '\tAv = reinterpret( A, 0 ); Bv = reinterpret( B, 0 ); Cv = reinterpret( C, 0 );' );
	w( '\toa2 = oa * 2; ob2 = ob * 2; oc2 = oc * 2;' );
	w( '\tsa1 *= 2; sa2 *= 2; sb1 *= 2; sb2 *= 2;' );
	w( '\tar = nota ? sa1 : sa2; ak = nota ? sa2 : sa1;' );
	w( '\tbk = notb ? sb1 : sb2; bn = notb ? sb2 : sb1;' );
	w( '\tsc1d = sc1 * 2; sc2d = sc2 * 2;' );
	w( '' );
	// alpha === 0: scale C by beta (complex).
	w( '\tif ( alphaR === 0.0 && alphaI === 0.0 ) {' );
	w( '\t\tfor ( j = 0; j < N; j++ ) {' );
	w( '\t\t\tpc = oc2 + ( j * sc2d );' );
	w( '\t\t\tif ( betaR === 0.0 && betaI === 0.0 ) {' );
	w( '\t\t\t\tfor ( i = 0; i < M; i++ ) { Cv[ pc ] = 0.0; Cv[ pc + 1 ] = 0.0; pc += sc1d; }' );
	w( '\t\t\t} else {' );
	w( '\t\t\t\tfor ( i = 0; i < M; i++ ) { cR = Cv[ pc ]; cI = Cv[ pc + 1 ]; Cv[ pc ] = ( betaR * cR ) - ( betaI * cI ); Cv[ pc + 1 ] = ( betaR * cI ) + ( betaI * cR ); pc += sc1d; }' );
	w( '\t\t\t}' );
	w( '\t\t}' );
	w( '\t\treturn C;' );
	w( '\t}' );
	w( '' );
	w( '\tmb = M - ( M % ' + MR + ' );' );
	w( '\tnb = N - ( N % ' + NR + ' );' );
	w( '\tfor ( j = 0; j < nb; j += ' + NR + ' ) {' );
	w( '\t\tpb0 = ob2 + ( j * bn );' );
	for ( c = 1; c < NR; c++ ) { w( '\t\tpb'+c+' = pb'+(c-1)+' + bn;' ); }
	w( '\t\tfor ( i = 0; i < mb; i += ' + MR + ' ) {' );
	// zero complex accumulators:
	w( '\t\t\t' + accs.map( function ( a ) { return a+' = 0.0;'; } ).join( ' ' ) );
	w( '\t\t\tpa0 = oa2 + ( i * ar );' );
	for ( r = 1; r < MR; r++ ) { w( '\t\t\tpa'+r+' = pa'+(r-1)+' + ar;' ); }
	w( '\t\t\tfor ( l = 0; l < K; l++ ) {' );
	w( '\t\t\t\tpak = l * ak; pbk = l * bk;' );
	for ( r = 0; r < MR; r++ ) {
		w( '\t\t\t\ta'+r+'R = Av[ pa'+r+' + pak ]; a'+r+'I = csa * Av[ pa'+r+' + pak + 1 ];' );
	}
	for ( c = 0; c < NR; c++ ) {
		w( '\t\t\t\tb'+c+'R = Bv[ pb'+c+' + pbk ]; b'+c+'I = csb * Bv[ pb'+c+' + pbk + 1 ];' );
	}
	for ( c = 0; c < NR; c++ ) {
		for ( r = 0; r < MR; r++ ) {
			w( '\t\t\t\tc'+r+'_'+c+'R += ( a'+r+'R * b'+c+'R ) - ( a'+r+'I * b'+c+'I ); c'+r+'_'+c+'I += ( a'+r+'R * b'+c+'I ) + ( a'+r+'I * b'+c+'R );' );
		}
	}
	w( '\t\t\t}' );
	// write-back tile:
	w( '\t\t\tpc = oc2 + ( i * sc1d ) + ( j * sc2d );' );
	w( '\t\t\tif ( betaR === 0.0 && betaI === 0.0 ) {' );
	for ( c = 0; c < NR; c++ ) {
		w( '\t\t\t\tpcc = pc' + ( c ? ' + ( ' + c + ' * sc2d )' : '' ) + ';' );
		for ( r = 0; r < MR; r++ ) {
			var idx = 'pcc' + ( r ? ' + ( ' + r + ' * sc1d )' : '' );
			w( '\t\t\t\tsR = c'+r+'_'+c+'R; sI = c'+r+'_'+c+'I; Cv[ '+idx+' ] = ( alphaR * sR ) - ( alphaI * sI ); Cv[ ( '+idx+' ) + 1 ] = ( alphaR * sI ) + ( alphaI * sR );' );
		}
	}
	w( '\t\t\t} else {' );
	for ( c = 0; c < NR; c++ ) {
		w( '\t\t\t\tpcc = pc' + ( c ? ' + ( ' + c + ' * sc2d )' : '' ) + ';' );
		for ( r = 0; r < MR; r++ ) {
			var idx2 = 'pcc' + ( r ? ' + ( ' + r + ' * sc1d )' : '' );
			w( '\t\t\t\tsR = c'+r+'_'+c+'R; sI = c'+r+'_'+c+'I; cR = Cv[ '+idx2+' ]; cI = Cv[ ( '+idx2+' ) + 1 ]; Cv[ '+idx2+' ] = ( alphaR * sR ) - ( alphaI * sI ) + ( betaR * cR ) - ( betaI * cI ); Cv[ ( '+idx2+' ) + 1 ] = ( alphaR * sI ) + ( alphaI * sR ) + ( betaR * cI ) + ( betaI * cR );' );
		}
	}
	w( '\t\t\t}' );
	w( '\t\t}' );
	w( '\t}' );
	// Edge cols [nb,N) over all rows, then edge rows [mb,M) over cols [0,nb):
	w( '\tfor ( jj = nb; jj < N; jj++ ) { edge( jj, 0 ); }' );
	w( '\tfor ( jj = 0; jj < nb; jj++ ) { edge( jj, mb ); }' );
	w( '\treturn C;' );
	w( '' );
	// Scalar complex-dot cleanup for a single column jj, rows [i0,M).
	w( '\tfunction edge( jj, i0 ) {' );
	w( '\t\tvar pbj, paj, l2, tR, tI, aRe, aIm, bRe, bIm, cRe, cIm, pcj, ii2;' );
	w( '\t\tpbj = ob2 + ( jj * bn );' );
	w( '\t\tfor ( ii2 = i0; ii2 < M; ii2++ ) {' );
	w( '\t\t\ttR = 0.0; tI = 0.0; paj = oa2 + ( ii2 * ar );' );
	w( '\t\t\tfor ( l2 = 0; l2 < K; l2++ ) {' );
	w( '\t\t\t\taRe = Av[ paj + ( l2 * ak ) ]; aIm = csa * Av[ paj + ( l2 * ak ) + 1 ];' );
	w( '\t\t\t\tbRe = Bv[ pbj + ( l2 * bk ) ]; bIm = csb * Bv[ pbj + ( l2 * bk ) + 1 ];' );
	w( '\t\t\t\ttR += ( aRe * bRe ) - ( aIm * bIm ); tI += ( aRe * bIm ) + ( aIm * bRe );' );
	w( '\t\t\t}' );
	w( '\t\t\tpcj = oc2 + ( ii2 * sc1d ) + ( jj * sc2d );' );
	w( '\t\t\tif ( betaR === 0.0 && betaI === 0.0 ) {' );
	w( '\t\t\t\tCv[ pcj ] = ( alphaR * tR ) - ( alphaI * tI ); Cv[ pcj + 1 ] = ( alphaR * tI ) + ( alphaI * tR );' );
	w( '\t\t\t} else {' );
	w( '\t\t\t\tcRe = Cv[ pcj ]; cIm = Cv[ pcj + 1 ]; Cv[ pcj ] = ( alphaR * tR ) - ( alphaI * tI ) + ( betaR * cRe ) - ( betaI * cIm ); Cv[ pcj + 1 ] = ( alphaR * tI ) + ( alphaI * tR ) + ( betaR * cIm ) + ( betaI * cRe );' );
	w( '\t\t\t}' );
	w( '\t\t}' );
	w( '\t}' );
	w( '}' );
	w( '' );
	w( 'export default zgemm;' );
	w( '' );
	return L.join( '\n' );
}

// CLI: node gen-tile.js MRxNR [MRxNR ...]
var specs = process.argv.slice( 2 );
if ( specs.length === 0 ) { specs = [ '2x2', '4x2', '2x4', '1x4', '4x1', '3x2', '2x3' ]; }
specs.forEach( function ( spec ) {
	var m = spec.split( 'x' ).map( Number );
	var code = gen( m[0], m[1] );
	var file = path.join( __dirname, 'variants', 'gen-' + m[0] + 'x' + m[1] + '.js' );
	fs.writeFileSync( file, code );
	console.log( 'wrote ' + file );
} );
